begin;

create table if not exists public.active_verification_questions (
  id bigint generated by default as identity primary key,
  version integer not null check (version > 0),
  position smallint not null check (position between 1 and 4),
  prompt text not null check (length(trim(prompt)) > 0),
  expected_answer text not null check (length(trim(expected_answer)) > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (version, position)
);

create table if not exists public.active_access_verifications (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','granted','revoked')),
  verification_version integer,
  granted_at timestamptz,
  revoked_at timestamptz,
  granted_by uuid,
  revoked_by uuid,
  revoke_reason text,
  last_attempt_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.active_verification_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  verification_version integer not null,
  score smallint not null check (score between 0 and 4),
  passed boolean not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz not null default now(),
  cooldown_until timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.active_verification_answers (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.active_verification_attempts(id) on delete cascade,
  question_id bigint not null references public.active_verification_questions(id) on delete restrict,
  position smallint not null check (position between 1 and 4),
  prompt_snapshot text not null,
  submitted_answer text not null,
  normalized_answer text not null,
  correct boolean not null,
  created_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

create index if not exists active_attempts_user_created_idx
  on public.active_verification_attempts (user_id, completed_at desc);
create index if not exists active_access_status_idx
  on public.active_access_verifications (status, updated_at desc);

alter table public.active_verification_questions enable row level security;
alter table public.active_verification_questions force row level security;
alter table public.active_access_verifications enable row level security;
alter table public.active_access_verifications force row level security;
alter table public.active_verification_attempts enable row level security;
alter table public.active_verification_attempts force row level security;
alter table public.active_verification_answers enable row level security;
alter table public.active_verification_answers force row level security;

insert into public.active_verification_questions(version, position, prompt, expected_answer, active)
values
  (1, 1, 'Quel logiciel est utilisé pour rédiger les procès-verbaux ?', 'LRPPN', true),
  (1, 2, 'Comment s’appelle l’application utilisée sur NEO pour communiquer par radio ?', 'STORM', true),
  (1, 3, 'Quel est l’indicatif d’un brigadier-chef au sein d’un équipage ?', 'TR', true),
  (1, 4, 'Comment s’appelle le portail permettant d’accéder aux applications et fichiers de police autorisés ?', 'CHEOPS', true)
on conflict (version, position) do update
set prompt = excluded.prompt, expected_answer = excluded.expected_answer,
    active = excluded.active, updated_at = now();

create or replace function public.active_normalize_answer(p_value text)
returns text language sql immutable strict
set search_path = '' as $$
  select lower(regexp_replace(
    replace(replace(replace(replace(trim(p_value), chr(8217), ''), chr(8216), ''), chr(96), ''), chr(39), ''),
    '\s+', ' ', 'g'));
$$;

create or replace function public.active_admin_guard()
returns public.admin_users language plpgsql security definer
set search_path = public, auth as $$
declare v_admin public.admin_users;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  select * into v_admin from public.admin_users
   where auth_uid = auth.uid() and coalesce(disabled,false)=false
     and (locked_until is null or locked_until <= now())
     and (expires_at is null or expires_at > now())
     and role in ('owner','admin') limit 1;
  if v_admin.id is null then raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  if not public.admin_require_aal2() then
    raise exception 'ADMIN_2FA_REQUIRED' using errcode='42501';
  end if;
  return v_admin;
end;
$$;

create or replace function public.active_access_status()
returns jsonb language plpgsql security definer
set search_path = public, auth as $$
declare v_access public.active_access_verifications; v_cooldown timestamptz;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  select * into v_access from public.active_access_verifications where user_id=auth.uid();
  select max(cooldown_until) into v_cooldown from public.active_verification_attempts
   where user_id=auth.uid() and cooldown_until > now();
  return jsonb_build_object(
    'status', coalesce(v_access.status,'pending'),
    'granted', coalesce(v_access.status='granted',false),
    'version', v_access.verification_version,
    'granted_at', v_access.granted_at,
    'revoked_at', v_access.revoked_at,
    'cooldown_until', v_cooldown
  );
end;
$$;

create or replace function public.active_verification_get_questions()
returns table(id bigint, "position" smallint, prompt text, version integer)
language plpgsql security definer set search_path = public, auth as $$
declare v_version integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  select max(q.version) into v_version from public.active_verification_questions q where q.active;
  if (select count(*) from public.active_verification_questions q where q.active and q.version=v_version) <> 4
    then raise exception 'ACTIVE_QUESTION_SET_INVALID'; end if;
  return query select q.id,q.position,q.prompt,q.version
    from public.active_verification_questions q
    where q.active and q.version=v_version order by q.position;
end;
$$;

create or replace function public.active_verification_submit(p_answers jsonb)
returns jsonb language plpgsql security definer set search_path = public, auth as $$
declare
  v_uid uuid := auth.uid(); v_version integer; v_score smallint := 0;
  v_attempt uuid := gen_random_uuid(); v_item jsonb; v_question public.active_verification_questions;
  v_answer text; v_failed_count integer; v_cooldown timestamptz; v_existing text;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  if jsonb_typeof(p_answers) <> 'array' or jsonb_array_length(p_answers) <> 4
    then raise exception 'FOUR_ANSWERS_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtext(v_uid::text));
  select max(q.version) into v_version from public.active_verification_questions q where q.active;
  select max(cooldown_until) into v_cooldown from public.active_verification_attempts
    where user_id=v_uid and cooldown_until > now();
  if v_cooldown is not null then
    return jsonb_build_object('passed',false,'score',null,'status','cooldown','cooldown_until',v_cooldown);
  end if;
  if (select count(distinct (x->>'question_id')::bigint) from jsonb_array_elements(p_answers) x) <> 4
    then raise exception 'DUPLICATE_QUESTION'; end if;
  insert into public.active_verification_attempts(id,user_id,verification_version,score,passed)
    values(v_attempt,v_uid,v_version,0,false);
  for v_item in select * from jsonb_array_elements(p_answers) loop
    select * into v_question from public.active_verification_questions
      where id=(v_item->>'question_id')::bigint and active and version=v_version;
    if v_question.id is null then raise exception 'INVALID_QUESTION'; end if;
    v_answer := coalesce(v_item->>'answer','');
    if public.active_normalize_answer(v_answer)=public.active_normalize_answer(v_question.expected_answer)
      then v_score := v_score+1; end if;
    insert into public.active_verification_answers(
      attempt_id,question_id,position,prompt_snapshot,submitted_answer,normalized_answer,correct)
    values(v_attempt,v_question.id,v_question.position,v_question.prompt,v_answer,
      public.active_normalize_answer(v_answer),
      public.active_normalize_answer(v_answer)=public.active_normalize_answer(v_question.expected_answer));
  end loop;
  select status into v_existing from public.active_access_verifications where user_id=v_uid;
  select count(*) into v_failed_count from public.active_verification_attempts
    where user_id=v_uid and not passed and completed_at > now()-interval '10 minutes';
  if v_score < 4 and v_failed_count >= 2 then v_cooldown := now()+interval '10 minutes'; end if;
  update public.active_verification_attempts set score=v_score,passed=(v_score=4),
    completed_at=now(),cooldown_until=v_cooldown where id=v_attempt;
  insert into public.active_access_verifications(user_id,status,verification_version,granted_at,last_attempt_at,updated_at)
  values(v_uid,case when v_score=4 then 'granted' else 'pending' end,v_version,
    case when v_score=4 then now() end,now(),now())
  on conflict(user_id) do update set
    status=case when v_score=4 then 'granted'
                when active_access_verifications.status='granted' then 'granted'
                else 'pending' end,
    verification_version=case when v_score=4 then v_version else active_access_verifications.verification_version end,
    granted_at=case when v_score=4 then coalesce(active_access_verifications.granted_at,now()) else active_access_verifications.granted_at end,
    revoked_at=case when v_score=4 then null else active_access_verifications.revoked_at end,
    revoke_reason=case when v_score=4 then null else active_access_verifications.revoke_reason end,
    last_attempt_at=now(),updated_at=now();
  return jsonb_build_object('attempt_id',v_attempt,'passed',v_score=4,'score',v_score,
    'status',case when v_score=4 then 'granted' else 'pending' end,'cooldown_until',v_cooldown);
end;
$$;

create or replace function public.admin_active_access_list(p_status text default null, p_search text default null)
returns table(user_id uuid,email text,status text,verification_version integer,granted_at timestamptz,
 revoked_at timestamptz,last_attempt_at timestamptz,attempts bigint,last_score smallint)
language plpgsql security definer set search_path=public,auth as $$
begin
  perform public.active_admin_guard();
  return query
  select u.id,u.email::text,coalesce(v.status,'pending'),v.verification_version,v.granted_at,v.revoked_at,v.last_attempt_at,
    count(a.id), (array_agg(a.score order by a.completed_at desc) filter(where a.id is not null))[1]
  from auth.users u left join public.active_access_verifications v on v.user_id=u.id
  left join public.active_verification_attempts a on a.user_id=u.id
  where (p_status is null or p_status='' or coalesce(v.status,'pending')=p_status)
    and (p_search is null or p_search='' or u.email ilike '%'||p_search||'%' or u.id::text ilike '%'||p_search||'%')
  group by u.id,u.email,v.user_id,v.status,v.verification_version,v.granted_at,v.revoked_at,v.last_attempt_at,v.updated_at
  having v.user_id is not null or count(a.id)>0
  order by v.updated_at desc nulls last;
end;
$$;

create or replace function public.admin_active_access_detail(p_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  perform public.active_admin_guard();
  return jsonb_build_object(
    'access',(select to_jsonb(v) from public.active_access_verifications v where v.user_id=p_user_id),
    'attempts',coalesce((select jsonb_agg(jsonb_build_object(
      'id',a.id,'score',a.score,'passed',a.passed,'completed_at',a.completed_at,'cooldown_until',a.cooldown_until,
      'answers',(select coalesce(jsonb_agg(jsonb_build_object('position',x.position,'prompt',x.prompt_snapshot,
        'answer',x.submitted_answer,'correct',x.correct) order by x.position),'[]'::jsonb)
        from public.active_verification_answers x where x.attempt_id=a.id)
      ) order by a.completed_at desc) from public.active_verification_attempts a where a.user_id=p_user_id),'[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_active_access_set(p_user_id uuid,p_action text,p_reason text default null)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_admin public.admin_users; v_old jsonb; v_new jsonb; v_version int;
begin
  v_admin := public.active_admin_guard();
  if v_admin.role <> 'owner' then
    raise exception 'OWNER_REQUIRED' using errcode='42501';
  end if;
  if p_action not in ('grant','restore','revoke') then raise exception 'INVALID_ACTION'; end if;
  select max(q.version) into v_version from public.active_verification_questions q where q.active;
  select to_jsonb(v) into v_old from public.active_access_verifications v where user_id=p_user_id;
  insert into public.active_access_verifications(user_id,status,verification_version,granted_at,revoked_at,granted_by,revoked_by,revoke_reason,updated_at)
  values(p_user_id,case when p_action='revoke' then 'revoked' else 'granted' end,v_version,
    case when p_action<>'revoke' then now() end,case when p_action='revoke' then now() end,
    case when p_action<>'revoke' then auth.uid() end,case when p_action='revoke' then auth.uid() end,
    case when p_action='revoke' then nullif(trim(p_reason),'') end,now())
  on conflict(user_id) do update set status=excluded.status,verification_version=excluded.verification_version,
    granted_at=excluded.granted_at,revoked_at=excluded.revoked_at,granted_by=excluded.granted_by,
    revoked_by=excluded.revoked_by,revoke_reason=excluded.revoke_reason,updated_at=now();
  select to_jsonb(v) into v_new from public.active_access_verifications v where user_id=p_user_id;
  insert into public.admin_audit_logs(actor_admin_id,actor_auth_uid,actor_email,actor_role,target_table,target_id,
    action,severity,success,old_value,new_value,comment,meta)
  values(v_admin.id,auth.uid(),v_admin.email,v_admin.role,'active_access_verifications',p_user_id::text,
    'active_access_'||p_action,'warning',true,v_old,v_new,p_reason,jsonb_build_object('source','admin_panel'));
  return v_new;
end;
$$;

revoke all on public.active_verification_questions,public.active_access_verifications,
  public.active_verification_attempts,public.active_verification_answers from public,anon,authenticated;
revoke all on function public.active_normalize_answer(text) from public,anon,authenticated;
revoke all on function public.active_admin_guard() from public,anon,authenticated;
revoke all on function public.active_access_status() from public,anon;
revoke all on function public.active_verification_get_questions() from public,anon;
revoke all on function public.active_verification_submit(jsonb) from public,anon;
revoke all on function public.admin_active_access_list(text,text) from public,anon;
revoke all on function public.admin_active_access_detail(uuid) from public,anon;
revoke all on function public.admin_active_access_set(uuid,text,text) from public,anon;
grant execute on function public.active_access_status() to authenticated;
grant execute on function public.active_verification_get_questions() to authenticated;
grant execute on function public.active_verification_submit(jsonb) to authenticated;
grant execute on function public.admin_active_access_list(text,text) to authenticated;
grant execute on function public.admin_active_access_detail(uuid) to authenticated;
grant execute on function public.admin_active_access_set(uuid,text,text) to authenticated;

commit;
