-- COP'IQ — centre de correction des signalements.
-- Tables et colonnes vérifiées sur la base de production le 23/08/2026.

begin;

create table if not exists public.admin_report_notes (
  id bigint generated by default as identity primary key,
  report_kind text not null check (report_kind in ('cas_pratique','question','culture','psy','bug','contact','forum')),
  report_id text not null,
  note text not null check (char_length(trim(note)) between 1 and 4000),
  actor_auth_uid uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists admin_report_notes_report_idx
  on public.admin_report_notes(report_kind, report_id, created_at desc);
alter table public.admin_report_notes enable row level security;
revoke all on public.admin_report_notes from public, anon;
grant select, insert on public.admin_report_notes to authenticated, service_role;
drop policy if exists admin_report_notes_staff_read on public.admin_report_notes;
create policy admin_report_notes_staff_read on public.admin_report_notes for select to authenticated
  using (public.has_admin_permission('reports.read'));
drop policy if exists admin_report_notes_staff_insert on public.admin_report_notes;
create policy admin_report_notes_staff_insert on public.admin_report_notes for insert to authenticated
  with check (public.has_admin_permission('reports.manage') and actor_auth_uid=(select auth.uid()));

create or replace function public.admin_report_center_list(
  p_kind text default null, p_status text default null, p_search text default null,
  p_limit integer default 150, p_offset integer default 0
) returns table(
  kind text,id text,created_at timestamptz,status text,module text,category text,
  question_id text,question text,message text,report_type text,email text,archived boolean
) language plpgsql security definer set search_path=pg_catalog,public,auth as $$
begin
  if not public.has_admin_permission('reports.read') then raise exception 'Accès refusé.' using errcode='42501'; end if;
  return query
  select * from (
    select 'culture'::text as kind,r.id::text as id,r.created_at,r.status,r.module,r.category,r.question_id::text as question_id,
      r.question,r.message,r.report_type,r.email,r.archived from public.report_culture_generale r
    union all
    select 'psy',r.id::text,r.created_at,r.status,r.module,r.category,r.question_id,r.question,r.message,
      r.report_type,r.email,r.archived from public.tests_psycotechnique_report r
    union all
    select 'cas_pratique',r.id::text,r.created_at,r.status,'cas_pratique',th.slug,r.question_id::text,
      c.title||' — Q'||q.position::text||' : '||q.label,r.message,r.report_type,au.email,r.archived
      from public.cas_pratique_question_reports r join public.cas_pratique_questions q on q.id=r.question_id
      join public.cas_pratique_cases c on c.id=r.case_id left join public.cas_pratique_themes th on th.id=c.theme_id
      left join auth.users au on au.id=r.user_id
    union all
    select 'question',r.id::text,r.created_at,r.status,r.source_file,r.question_category,null,r.question_text,
      r.report_message,r.report_type,r.email,r.archived from public.report_question r
    union all
    select 'bug',r.id::text,r.created_at,coalesce(r.status,'new'),'application',r.category,null,r.title,r.message,
      r.severity,r.email,false from public.bug_reports r
    union all
    select 'contact',r.id::text,r.created_at,r.status,'contact',null,null,r.subject,r.message,null,r.email,
      (r.status='archived') from public.contact_messages r
    union all
    select 'forum',r.id::text,r.created_at,r.status,'forum',r.target_type,r.target_id::text,
      r.target_type||' #'||r.target_id::text,r.details,r.reason,null,false from public.community_reports r
  ) u
  where (p_kind is null or p_kind='' or u.kind=case when p_kind='cg' then 'culture' else p_kind end)
    and (p_status is null or p_status='' or
      (p_status='archived' and u.archived) or (p_status<>'archived' and u.status=p_status))
    and (p_search is null or trim(p_search)='' or u.id=p_search or coalesce(u.question_id,'')=p_search
      or coalesce(u.question,'') ilike '%'||p_search||'%' or coalesce(u.message,'') ilike '%'||p_search||'%'
      or coalesce(u.email,'') ilike '%'||p_search||'%' or coalesce(u.report_type,'') ilike '%'||p_search||'%')
  order by u.created_at desc limit least(greatest(p_limit,1),300) offset greatest(p_offset,0);
end $$;

create or replace function public.admin_report_inspect(p_kind text,p_id text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare r jsonb; target jsonb; target_table text; v_category text; v_qid text; v_case uuid;
begin
  if not public.has_admin_permission('reports.read') then raise exception 'Accès refusé.' using errcode='42501'; end if;
  p_kind:=case when p_kind='cg' then 'culture' else p_kind end;
  if p_kind='psy' then
    select to_jsonb(x),x.category,x.question_id into r,v_category,v_qid from public.tests_psycotechnique_report x where x.id::text=p_id;
    target_table:=case v_category when 'attention_visuelle' then 'tests_psyco_attention_visuelle'
      when 'calcul_mental' then 'tests_psyco_calcul_mental' when 'concentration' then 'tests_psyco_concentration'
      when 'logique_verbale' then 'tests_psyco_logique_verbale' when 'raisonnement_logique' then 'tests_psyco_raisonnement_logique'
      when 'raisonnement_spatial' then 'tests_psyco_raisonnement_spatial' when 'rotations_symetries' then 'tests_psyco_rotations_symetries'
      when 'suite_logique' then 'tests_psyco_suite_logique' when 'suites_logiques' then 'tests_psyco_suite_logique' end;
    if target_table is not null and v_qid is not null then
      if target_table='tests_psyco_attention_visuelle' then
        if v_qid ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
          execute format('select to_jsonb(t) from public.%I t where id=$1::uuid',target_table) into target using v_qid;
        end if;
      elsif v_qid ~ '^[0-9]+$' then
        execute format('select to_jsonb(t) from public.%I t where id=$1::bigint',target_table) into target using v_qid;
      end if;
    end if;
  elsif p_kind='culture' then
    select to_jsonb(x),x.question_id::text into r,v_qid from public.report_culture_generale x where x.id::text=p_id;
    target_table:='quiz_questions'; select to_jsonb(t) into target from public.quiz_questions t where t.id::text=v_qid;
  elsif p_kind='cas_pratique' then
    select to_jsonb(x),x.case_id into r,v_case from public.cas_pratique_question_reports x where x.id::text=p_id;
    target_table:='cas_pratique_questions';
    select jsonb_build_object('question',to_jsonb(q),'case',to_jsonb(c),'perfect_answer',to_jsonb(pa),
      'rubric_points',coalesce((select jsonb_agg(to_jsonb(rp) order by rp.position) from public.cas_pratique_rubric_points rp where rp.question_id=q.id),'[]'::jsonb))
      into target from public.cas_pratique_questions q join public.cas_pratique_cases c on c.id=q.case_id
      left join public.cas_pratique_perfect_answers pa on pa.question_id=q.id
      where q.id=(r->>'question_id')::uuid;
  elsif p_kind='question' then
    select to_jsonb(x) into r from public.report_question x where x.id::text=p_id; target_table:=null;
  elsif p_kind='bug' then
    select to_jsonb(x) into r from public.bug_reports x where x.id::text=p_id; target:=r; target_table:='bug_reports';
  elsif p_kind='contact' then
    select to_jsonb(x) into r from public.contact_messages x where x.id::text=p_id; target:=r; target_table:='contact_messages';
  elsif p_kind='forum' then
    select to_jsonb(x) into r from public.community_reports x where x.id::text=p_id; target_table:='community_reports';
  else raise exception 'Type de signalement inconnu.' using errcode='22023'; end if;
  if r is null then raise exception 'Signalement introuvable.' using errcode='P0002'; end if;
  return jsonb_build_object('report',r,'target',target,'target_table',target_table,'target_found',target is not null,
    'can_edit',case when p_kind in ('psy','culture','cas_pratique') then public.has_admin_permission('quiz.write') or public.has_admin_permission('cas_pratiques') else public.has_admin_permission('reports.manage') end,
    'can_delete_report',public.has_admin_permission('reports.manage'),'can_delete_target',public.has_admin_role('owner'),
    'notes',coalesce((select jsonb_agg(to_jsonb(n) order by n.created_at) from public.admin_report_notes n where n.report_kind=p_kind and n.report_id=p_id),'[]'::jsonb),
    'history',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at) from public.admin_audit_logs a
      where a.meta->>'report_kind'=p_kind and a.meta->>'report_id'=p_id),'[]'::jsonb));
end $$;

create or replace function public.admin_report_add_note(p_kind text,p_id text,p_note text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare n public.admin_report_notes;
begin
  if not public.has_admin_permission('reports.manage') then raise exception 'Accès refusé.' using errcode='42501'; end if;
  insert into public.admin_report_notes(report_kind,report_id,note) values(case when p_kind='cg' then 'culture' else p_kind end,p_id,trim(p_note)) returning * into n;
  perform public.audit_log_write('report.note','info',true,'admin_report_notes',n.id::text,null,null,to_jsonb(n),p_note);
  return to_jsonb(n);
end $$;

create or replace function public.admin_report_set_status(p_kind text,p_id text,p_status text,p_archive boolean default false,p_note text default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare old_row jsonb; new_row jsonb; n integer; t text;
begin
  if not public.has_admin_permission('reports.manage') then raise exception 'Accès refusé.' using errcode='42501'; end if;
  p_kind:=case when p_kind='cg' then 'culture' else p_kind end;
  if p_kind='psy' then t:='tests_psycotechnique_report'; select to_jsonb(x) into old_row from public.tests_psycotechnique_report x where x.id::text=p_id for update;
    update public.tests_psycotechnique_report set status=p_status,archived=p_archive,status_updated_at=now(),updated_at=now() where id::text=p_id returning to_jsonb(tests_psycotechnique_report.*) into new_row;
  elsif p_kind='culture' then t:='report_culture_generale'; select to_jsonb(x) into old_row from public.report_culture_generale x where x.id::text=p_id for update;
    update public.report_culture_generale set status=p_status,archived=p_archive,status_updated_at=now(),updated_at=now() where id::text=p_id returning to_jsonb(report_culture_generale.*) into new_row;
  elsif p_kind='cas_pratique' then t:='cas_pratique_question_reports'; select to_jsonb(x) into old_row from public.cas_pratique_question_reports x where x.id::text=p_id for update;
    update public.cas_pratique_question_reports set status=p_status,archived=p_archive,admin_response=coalesce(p_note,admin_response),resolved_by=case when p_status='resolved' then auth.uid() else null end,resolved_at=case when p_status='resolved' then now() else null end,updated_at=now() where id::text=p_id returning to_jsonb(cas_pratique_question_reports.*) into new_row;
  elsif p_kind='question' then t:='report_question'; select to_jsonb(x) into old_row from public.report_question x where x.id::text=p_id for update;
    update public.report_question set status=p_status,archived=p_archive,updated_at=now() where id::text=p_id returning to_jsonb(report_question.*) into new_row;
  elsif p_kind='bug' then t:='bug_reports'; select to_jsonb(x) into old_row from public.bug_reports x where x.id::text=p_id for update;
    update public.bug_reports set status=p_status where id::text=p_id returning to_jsonb(bug_reports.*) into new_row;
  elsif p_kind='contact' then t:='contact_messages'; select to_jsonb(x) into old_row from public.contact_messages x where x.id::text=p_id for update;
    update public.contact_messages set status=case when p_archive then 'archived' else p_status end where id::text=p_id returning to_jsonb(contact_messages.*) into new_row;
  elsif p_kind='forum' then t:='community_reports'; select to_jsonb(x) into old_row from public.community_reports x where x.id::text=p_id for update;
    update public.community_reports set status=p_status,resolution=coalesce(p_note,resolution),resolved_at=case when p_status='resolved' then now() else null end where id::text=p_id returning to_jsonb(community_reports.*) into new_row;
  else raise exception 'Type inconnu.' using errcode='22023'; end if;
  get diagnostics n=row_count; if n<>1 then raise exception 'Signalement introuvable.' using errcode='P0002'; end if;
  if p_note is not null and trim(p_note)<>'' then perform public.admin_report_add_note(p_kind,p_id,p_note); end if;
  perform public.audit_log_write(case when p_status='new' then 'report.reopen' else 'report.status' end,'info',true,t,p_id,null,old_row,new_row,p_note);
  update public.admin_audit_logs set meta=meta||jsonb_build_object('report_kind',p_kind,'report_id',p_id) where id=(select max(id) from public.admin_audit_logs where actor_auth_uid=auth.uid());
  return jsonb_build_object('ok',true,'report',new_row);
end $$;

create or replace function public.admin_report_update_target(p_kind text,p_id text,p_expected jsonb,p_patch jsonb,p_resolve boolean default false)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare info jsonb; old_row jsonb; new_row jsonb; target_table text; qid text; cat text; n integer;
begin
  if not (public.has_admin_permission('quiz.write') or public.has_admin_permission('cas_pratiques')) then raise exception 'Accès refusé.' using errcode='42501'; end if;
  p_kind:=case when p_kind='cg' then 'culture' else p_kind end;
  info:=public.admin_report_inspect(p_kind,p_id); old_row:=info->'target'; target_table:=info->>'target_table';
  if old_row is null or old_row='null'::jsonb then raise exception 'Ressource introuvable.' using errcode='P0002'; end if;
  if p_expected is distinct from old_row then raise exception 'Cette ressource a été modifiée depuis son ouverture.' using errcode='40001'; end if;
  if p_kind='culture' then
    qid:=info->'report'->>'question_id';
    if nullif(trim(p_patch->>'question'),'') is null then raise exception 'La question est obligatoire.' using errcode='22023'; end if;
    if jsonb_typeof(p_patch->'options')<>'array' or jsonb_array_length(p_patch->'options')<2 then raise exception 'Les réponses sont invalides.' using errcode='22023'; end if;
    if not (p_patch->'options' @> jsonb_build_array(p_patch->>'answer')) then raise exception 'La bonne réponse doit être présente.' using errcode='22023'; end if;
    update public.quiz_questions set question=p_patch->>'question',options=p_patch->'options',answer=p_patch->>'answer',
      explanation=p_patch->>'explanation',category=p_patch->>'category',difficulty=p_patch->>'difficulty',sub=p_patch->>'sub'
      where id::text=qid returning to_jsonb(quiz_questions.*) into new_row;
  elsif p_kind='cas_pratique' then
    qid:=info->'report'->>'question_id';
    update public.cas_pratique_questions set label=coalesce(nullif(trim(p_patch->>'label'),''),label),
      hint=case when p_patch?'hint' then p_patch->>'hint' else hint end,max_points=coalesce((p_patch->>'max_points')::int,max_points),
      char_min=coalesce((p_patch->>'char_min')::int,char_min),char_recommended=coalesce((p_patch->>'char_recommended')::int,char_recommended)
      where id::text=qid returning to_jsonb(cas_pratique_questions.*) into new_row;
  elsif p_kind='psy' then
    qid:=info->'report'->>'question_id'; cat:=info->'report'->>'category';
    if target_table='tests_psyco_attention_visuelle' then
      update public.tests_psyco_attention_visuelle set text_a=coalesce(p_patch->>'text_a',text_a),text_b=coalesce(p_patch->>'text_b',text_b),
        is_true=coalesce((p_patch->>'is_true')::boolean,is_true),difficulty=coalesce(p_patch->>'difficulty',difficulty),
        explanation=case when p_patch?'explanation' then p_patch->>'explanation' else explanation end,is_active=coalesce((p_patch->>'is_active')::boolean,is_active)
        where id=qid::uuid returning to_jsonb(tests_psyco_attention_visuelle.*) into new_row;
    elsif target_table='tests_psyco_suite_logique' then
      update public.tests_psyco_suite_logique set sequence_text=coalesce(nullif(trim(p_patch->>'sequence_text'),''),sequence_text),
        options=case when p_patch?'options' then array(select jsonb_array_elements_text(p_patch->'options')) else options end,
        answer=coalesce(p_patch->>'answer',answer),explanation=case when p_patch?'explanation' then p_patch->>'explanation' else explanation end,
        difficulty=coalesce(p_patch->>'difficulty',difficulty),hint=case when p_patch?'hint' then p_patch->>'hint' else hint end,is_active=coalesce((p_patch->>'is_active')::boolean,is_active)
        where id=qid::bigint returning to_jsonb(tests_psyco_suite_logique.*) into new_row;
    elsif target_table in ('tests_psyco_raisonnement_spatial','tests_psyco_rotations_symetries') then
      execute format('update public.%I set question=coalesce(nullif(trim($2->>''question''),''''),question), options=case when $2?''options'' then $2->''options'' else options end, answer=coalesce($2->>''answer'',answer), explanation=case when $2?''explanation'' then $2->>''explanation'' else explanation end, difficulty=coalesce($2->>''difficulty'',difficulty), hint=case when $2?''hint'' then $2->>''hint'' else hint end, is_active=coalesce(($2->>''is_active'')::boolean,is_active) where id=$1::bigint returning to_jsonb(%I.*)',target_table,target_table) into new_row using qid,p_patch;
    elsif target_table in ('tests_psyco_calcul_mental','tests_psyco_concentration','tests_psyco_logique_verbale','tests_psyco_raisonnement_logique') then
      execute format('update public.%I set question=coalesce(nullif(trim($2->>''question''),''''),question), options=case when $2?''options'' then array(select jsonb_array_elements_text($2->''options'')) else options end, answer=coalesce($2->>''answer'',answer), explanation=case when $2?''explanation'' then $2->>''explanation'' else explanation end, difficulty=coalesce($2->>''difficulty'',difficulty), hint=case when $2?''hint'' then $2->>''hint'' else hint end, is_active=coalesce(($2->>''is_active'')::boolean,is_active) where id=$1::bigint returning to_jsonb(%I.*)',target_table,target_table) into new_row using qid,p_patch;
    else raise exception 'Catégorie psychotechnique non prise en charge.' using errcode='22023'; end if;
  else raise exception 'Ce type ne possède pas d’éditeur de contenu.' using errcode='22023'; end if;
  if new_row is null then raise exception 'La base n’a modifié aucune ligne.' using errcode='P0002'; end if;
  perform public.audit_log_write('content.corrected','info',true,target_table,qid,null,old_row,new_row,'Correction depuis un signalement');
  update public.admin_audit_logs set meta=meta||jsonb_build_object('report_kind',p_kind,'report_id',p_id) where id=(select max(id) from public.admin_audit_logs where actor_auth_uid=auth.uid());
  if p_resolve then perform public.admin_report_set_status(p_kind,p_id,'resolved',false,'Contenu corrigé et vérifié'); end if;
  return jsonb_build_object('ok',true,'target',new_row,'report_resolved',p_resolve);
end $$;

create or replace function public.admin_report_delete(p_kind text,p_id text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare old_row jsonb; n integer; t text;
begin
  if not public.has_admin_permission('reports.manage') then raise exception 'Accès refusé.' using errcode='42501'; end if;
  p_kind:=case when p_kind='cg' then 'culture' else p_kind end;
  t:=case p_kind when 'psy' then 'tests_psycotechnique_report' when 'culture' then 'report_culture_generale'
    when 'cas_pratique' then 'cas_pratique_question_reports' when 'question' then 'report_question'
    when 'bug' then 'bug_reports' when 'contact' then 'contact_messages' when 'forum' then 'community_reports' end;
  if t is null then raise exception 'Type inconnu.' using errcode='22023'; end if;
  execute format('select to_jsonb(x) from public.%I x where id::text=$1 for update',t) into old_row using p_id;
  if old_row is null then raise exception 'Signalement introuvable.' using errcode='P0002'; end if;
  execute format('delete from public.%I where id::text=$1',t) using p_id; get diagnostics n=row_count;
  perform public.audit_log_write('report.deleted','warning',n=1,t,p_id,null,old_row,null,'Suppression du signalement');
  return jsonb_build_object('ok',n=1);
end $$;

create or replace function public.admin_report_delete_target(p_kind text,p_id text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,auth as $$
declare info jsonb; old_row jsonb; t text; qid text; n integer;
begin
  if not public.has_admin_role('owner') then raise exception 'Suppression réservée au rôle owner.' using errcode='42501'; end if;
  info:=public.admin_report_inspect(p_kind,p_id); old_row:=info->'target';t:=info->>'target_table';qid:=info->'report'->>'question_id';
  if old_row is null or old_row='null'::jsonb or t is null or qid is null then raise exception 'Ressource introuvable ou non supprimable.' using errcode='P0002'; end if;
  if t not in ('quiz_questions','cas_pratique_questions','tests_psyco_attention_visuelle','tests_psyco_calcul_mental','tests_psyco_concentration','tests_psyco_logique_verbale','tests_psyco_raisonnement_logique','tests_psyco_raisonnement_spatial','tests_psyco_rotations_symetries','tests_psyco_suite_logique') then raise exception 'Table cible interdite.' using errcode='42501'; end if;
  execute format('delete from public.%I where id::text=$1',t) using qid; get diagnostics n=row_count;
  perform public.audit_log_write('content.deleted','critical',n=1,t,qid,null,old_row,null,'Suppression définitive depuis un signalement');
  update public.admin_audit_logs set meta=meta||jsonb_build_object('report_kind',case when p_kind='cg' then 'culture' else p_kind end,'report_id',p_id) where id=(select max(id) from public.admin_audit_logs where actor_auth_uid=auth.uid());
  return jsonb_build_object('ok',n=1,'deleted_table',t,'deleted_id',qid);
end $$;

revoke all on function public.admin_report_center_list(text,text,text,integer,integer) from public,anon;
revoke all on function public.admin_report_inspect(text,text) from public,anon;
revoke all on function public.admin_report_add_note(text,text,text) from public,anon;
revoke all on function public.admin_report_set_status(text,text,text,boolean,text) from public,anon;
revoke all on function public.admin_report_update_target(text,text,jsonb,jsonb,boolean) from public,anon;
revoke all on function public.admin_report_delete(text,text) from public,anon;
revoke all on function public.admin_report_delete_target(text,text) from public,anon;
grant execute on function public.admin_report_center_list(text,text,text,integer,integer) to authenticated,service_role;
grant execute on function public.admin_report_inspect(text,text) to authenticated,service_role;
grant execute on function public.admin_report_add_note(text,text,text) to authenticated,service_role;
grant execute on function public.admin_report_set_status(text,text,text,boolean,text) to authenticated,service_role;
grant execute on function public.admin_report_update_target(text,text,jsonb,jsonb,boolean) to authenticated,service_role;
grant execute on function public.admin_report_delete(text,text) to authenticated,service_role;
grant execute on function public.admin_report_delete_target(text,text) to authenticated,service_role;

notify pgrst,'reload schema';
commit;
