create table if not exists public.admin_report_email_notifications (
  id bigint generated by default as identity primary key,
  report_kind text not null,
  report_id text not null,
  recipient_email text not null,
  template text not null default 'resolved',
  status text not null default 'pending' check (status in ('pending','sent','failed')),
  provider_id text,
  error text,
  triggered_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (report_kind, report_id, template)
);

alter table public.admin_report_email_notifications enable row level security;
revoke all on table public.admin_report_email_notifications from public, anon, authenticated;
grant all on table public.admin_report_email_notifications to service_role;
grant usage, select on sequence public.admin_report_email_notifications_id_seq to service_role;

comment on table public.admin_report_email_notifications is
  'Journal idempotent des emails automatiques envoyés après traitement administratif d’un signalement.';
