-- Alignement final avec les appels ScolariteText réellement présents dans Flutter.
-- Ces 93 clés proviennent d'une version antérieure de l'extracteur et sont
-- conservées uniquement dans la piste d'audit.

update public.scolarite_content_fragments
set is_runtime_connected = false
where (source_path, fragment_key) in (
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/classification_infractions_contenu_page.dart', 'f00014'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/gpx_school_etendue_application_lois_page.dart', 'f00122'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/gpx_school_responsabilite_penale_causes_irresponsabilite_page.dart', 'f00220'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/gpx_school_responsabilite_penale_complicite_coaction_page.dart', 'f00158'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/gpx_school_responsabilite_penale_personnes_morales_page.dart', 'f00143'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/gpx_school_responsabilite_penale_principes_generaux_page.dart', 'f00033'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/loi_penale_contenu_page.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/droit_pénale_général_pages/responsabilite_penale_contenu.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/collectives/liberte_presse_page.dart', 'f00202'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/collectives/liberte_presse_page.dart', 'f00203'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/collectives/regime_manifestations_page.dart', 'f00128'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/collectives/regime_manifestations_page.dart', 'f00129'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties_protection_libertes_page.dart', 'f00013'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties_protection_libertes_page.dart', 'f00014'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/controle_constitutionnalite_lois_page.dart', 'f00112'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/controle_constitutionnalite_lois_page.dart', 'f00113'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_juridictionnels_page.dart', 'f00123'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_juridictionnels_page.dart', 'f00124'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_non_juridictionnels_page.dart', 'f00075'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_non_juridictionnels_page.dart', 'f00076'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_organes_internationaux_page.dart', 'f00051'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/garanties/recours_organes_internationaux_page.dart', 'f00052'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/cnil_protection_donnees_page.dart', 'f00100'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/cnil_protection_donnees_page.dart', 'f00101'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/droit_vie_privee_page.dart', 'f00443'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/droit_vie_privee_page.dart', 'f00444'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/liberte_aller_venir_detail_page.dart', 'f00170'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/liberte_aller_venir_detail_page.dart', 'f00171'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/respect_personne_legislation_page.dart', 'f00181'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/respect_personne_legislation_page.dart', 'f00182'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/surete_liberte_individuelle_page.dart', 'f00184'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/individuelles/surete_liberte_individuelle_page.dart', 'f00185'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction_libertes_publiques_page.dart', 'f00013'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction_libertes_publiques_page.dart', 'f00014'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/declaration_droits_homme_page.dart', 'f00055'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/declaration_droits_homme_page.dart', 'f00056'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/notion_libertes_publiques_page.dart', 'f00088'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/notion_libertes_publiques_page.dart', 'f00089'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/regime_juridique_libertes_publiques_page.dart', 'f00147'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/regime_juridique_libertes_publiques_page.dart', 'f00148'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/sources_libertes_publiques_page.dart', 'f00181'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/introduction/sources_libertes_publiques_page.dart', 'f00182'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/liberte_publiques_contenu_page.dart', 'f00011'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/liberte_publiques_contenu_page.dart', 'f00012'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/libertes_expression_collectives_page.dart', 'f00011'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/libertes_expression_collectives_page.dart', 'f00012'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/libertes_individuelles_vie_privee_page.dart', 'f00015'),
  ('lib/content/gpx_scolarite/dps_dpg/generalite_pages/libertés_publiques/libertes_individuelles_vie_privee_page.dart', 'f00016'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/conduite_stupefiants_contenu_page.dart', 'f00095'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/defaut_assurance_page.dart', 'f00062'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/defaut_permis_contenu_page.dart', 'f00069'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/delit_fuite_page.dart', 'f00096'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/etat_alcoolique_contenu_page.dart', 'f00124'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/incitation_organisation_promotion_page.dart', 'f00050'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/ivresse_contenu_page.dart', 'f00075'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/plaques_inscriptions_page.dart', 'f00065'),
  ('lib/content/gpx_scolarite/dps_dpg/infraction_circulation_routière_pages/refus_obtemperer_page.dart', 'f00080'),
  ('lib/content/gpx_scolarite/dps_dpg/libertés_publiques_pages/introduction/notion_libertes_publiques_page.dart', 'f00035'),
  ('lib/content/gpx_scolarite/dps_dpg/libertés_publiques_pages/libertes_publiques_introduction_contenu_page.dart', 'f00015'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/autorites_investies_contenu.dart', 'f00022'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/bracelet_contenu_page.dart', 'f00018'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/controle_judiciaire_contenu.dart', 'f00014'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/controle_mission_contenu_page.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/detention_provisoire_contenu.dart', 'f00018'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/instruction_preparatoire_contenu_detail.dart', 'f00021'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/instruction_preparatoire_contenu.dart', 'f00021'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/juridiction_contenu_page.dart', 'f00013'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/juridictions_execution_decisions_justice_page.dart', 'f00342'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/juridictions_execution_decisions_justice_page.dart', 'f00343'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/mandats_justice_contenu.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/nullite_contenu_page.dart', 'f00016'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_en_nullite_page.dart', 'f00116'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_action_civile_chapitre_1_titre_preliminaire_page.dart', 'f00152'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_action_civile_chapitre_2_sujets_action_publique_page.dart', 'f00174'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_action_civile_chapitre_3_exercice_action_publique_page.dart', 'f00250'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_action_civile_chapitre_4_extinction_action_publique_page.dart', 'f00163'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_action_civile_page.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_action_publique_autorites_pj_page.dart', 'f00017'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_chambre_instruction.dart', 'f00112'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_deroulement_detention_provisoire.dart', 'f00088'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_dispositions_mineurs_instruction_contenu.dart', 'f00013'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_effets_nullite_page.dart', 'f00064'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_fin_detention_provisoire.dart', 'f00125'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_instruction_cloture.dart', 'f00140'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_instruction_pouvoirs.dart', 'f00230'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_mandats_sanctions_irregularites.dart', 'f00069'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_nullites_substantielles_page.dart', 'f00062'),
  ('lib/content/gpx_scolarite/dps_dpg/procédure_pénale_pages/pp_reparation_detention_injustifiee.dart', 'f00059'),
  ('lib/content/gpx_scolarite/dps_dpg/stupéfiants_pages/blanchiment_produit_contenu_page.dart', 'f00079'),
  ('lib/content/gpx_scolarite/dps_dpg/stupéfiants_pages/cession_offre_contenu_page.dart', 'f00072'),
  ('lib/content/gpx_scolarite/dps_dpg/stupéfiants_pages/import_export_contenu_page.dart', 'f00082'),
  ('lib/content/gpx_scolarite/dps_dpg/stupéfiants_pages/transport_detention_offre_contenu_page.dart', 'f00103'),
  ('lib/content/gpx_scolarite/dps_dpg/stupéfiants_pages/usage_illicite_contenu_page.dart', 'f00091')
);

notify pgrst, 'reload schema';

