-- COP'IQ — couverture complète des cours de la catégorie Organisation PN.
-- Relançable : chaque question possède une clé stable et commune aux parcours GPX/PA.

with ranked as (
  select id, track,
         row_number() over (partition by track order by position, id) as rn
  from public.quiz_scolarite_questions
  where module in (
    'gpx_institutions_valeurs_quiz_institutions_valeurs_quiz_organisation_page',
    'pa_institutions_valeurs_quiz_pa_quiz_organisation_page'
  )
    and metadata->>'chapter_key' = 'organisation_pn'
    and category ~* 'Organisation PN — (DGPN|Directions|DNPAF|DNPJ|DNSP|DRHFS|IGPN|CRS|ADP|SDLP)'
), classified as (
  select id,
         case when rn <= 15 then 'organigramme_mi' else 'organigrammes_pn' end chapter_key
  from ranked where rn <= 30
)
update public.quiz_scolarite_questions q
set metadata = q.metadata || jsonb_build_object('chapter_key', c.chapter_key), updated_at = now()
from classified c where q.id = c.id;

-- Compléments ciblés issus des cours affichés dans l'application.
with questions(stable_key, chapter_key, category, difficulty, question, options, answer, explanation, legal_ref, position) as (
values
('emploi-01','regles_emploi_pa','Règles d’emploi PA','Facile','Dans quel cadre un policier adjoint peut-il employer son arme de service ?',jsonb_build_array('Uniquement dans le strict cadre prévu par la loi','Dès qu’une personne refuse un contrôle','À chaque fuite d’un suspect','Sur simple instruction orale d’un collègue'),'Uniquement dans le strict cadre prévu par la loi','L’emploi de l’arme n’est jamais une réponse automatique. Il suppose que les conditions légales soient réunies, notamment celles prévues par l’article L. 435-1 du Code de la sécurité intérieure ou par la légitime défense de l’article 122-5 du Code pénal.','CSI, art. L. 435-1 ; Code pénal, art. 122-5',2001),
('emploi-02','regles_emploi_pa','Règles d’emploi PA','Facile','Quelle tenue le policier adjoint porte-t-il en principe pendant son service ?',jsonb_build_array('La tenue d’uniforme','Une tenue civile choisie librement','Une tenue civile imposée pour chaque mission','Aucune règle particulière ne s’applique'),'La tenue d’uniforme','Le policier adjoint exerce normalement ses fonctions revêtu de sa tenue d’uniforme. Le port de la tenue civile demeure une exception : il doit être autorisé par le chef de service et justifié par la nature de la mission.','Cours COP’IQ — Règles d’emploi du policier adjoint',2002),
('emploi-03','regles_emploi_pa','Règles d’emploi PA','Moyenne','Qui délivre l’aptitude initiale au port et à l’emploi de l’arme de service ?',jsonb_build_array('La structure de formation compétente','Le service d’affectation après la formation','Le maire de la commune d’affectation','Tout moniteur présent dans le service'),'La structure de formation compétente','Cette aptitude relève exclusivement de la structure de formation. Le service d’affectation ne peut pas la délivrer a posteriori : cette distinction protège la sécurité de l’agent, de ses collègues et du public.','Cours COP’IQ — Règles d’emploi du policier adjoint',2003),
('emploi-04','regles_emploi_pa','Règles d’emploi PA','Moyenne','Que fait le PA doté d’une arme individuelle à la fin de son service quotidien ?',jsonb_build_array('Il la restitue selon les règles du service','Il l’emporte systématiquement à domicile','Il la prête à l’équipe suivante','Il la conserve dans son véhicule personnel'),'Il la restitue selon les règles du service','L’arme individuelle est retirée à la prise de service puis restituée à son issue. Son port est réservé au cadre du service et associé, sauf régime particulier légalement prévu, au port de l’uniforme.','Cours COP’IQ — Règles d’emploi du policier adjoint',2004),
('emploi-05','regles_emploi_pa','Règles d’emploi PA','Facile','Que doit faire immédiatement un PA en cas de perte, vol ou détérioration de son arme ou de ses munitions ?',jsonb_build_array('Le signaler immédiatement','Attendre la prochaine prise de service','Remplacer lui-même le matériel','Le déclarer uniquement si une enquête commence'),'Le signaler immédiatement','Tout incident concernant l’arme ou les munitions doit être signalé sans délai. Cette remontée immédiate permet de sécuriser la situation, d’engager les vérifications nécessaires et de préserver la traçabilité du matériel.','Cours COP’IQ — Règles d’emploi du policier adjoint',2005),
('emploi-06','regles_emploi_pa','Règles d’emploi PA','Facile','Quand le policier adjoint doit-il porter sa carte professionnelle ?',jsonb_build_array('Lorsqu’il est en service','Uniquement lors des cérémonies','Uniquement en dehors du service','Seulement après sa titularisation comme gardien de la paix'),'Lorsqu’il est en service','La carte professionnelle accompagne l’exercice des missions. Elle sert uniquement à des fins professionnelles, ne peut être prêtée ni reproduite et doit être restituée à la fin du contrat.','Cours COP’IQ — Règles d’emploi du policier adjoint',2006),
('emploi-07','regles_emploi_pa','Règles d’emploi PA','Moyenne','À quelles fins les locaux, matériels et véhicules confiés au PA peuvent-ils être utilisés ?',jsonb_build_array('Uniquement pour les besoins professionnels du service','Pour tout déplacement personnel court','Pour rendre service à un proche','Pour une activité privée autorisée oralement par un collègue'),'Uniquement pour les besoins professionnels du service','Les moyens de l’administration sont affectés au service. Le PA doit en prendre soin et ne les utiliser que professionnellement ; un usage étranger au service peut engager sa responsabilité disciplinaire.','Cours COP’IQ — Règles d’emploi du policier adjoint',2007),
('emploi-08','regles_emploi_pa','Règles d’emploi PA','Facile','Quel régime horaire s’applique au policier adjoint ?',jsonb_build_array('Celui de son service ou unité d’appartenance','Un horaire national fixe réservé aux PA','Uniquement un service de jour','Un horaire libre défini chaque semaine'),'Celui de son service ou unité d’appartenance','Le PA suit le régime de travail de l’unité qu’il assiste, de jour comme de nuit. En cas d’événement grave ou important, les nécessités du service peuvent conduire à le mobiliser en tout temps et en tout lieu.','Cours COP’IQ — Règles d’emploi du policier adjoint',2008),
('emploi-09','regles_emploi_pa','Règles d’emploi PA','Moyenne','Le policier adjoint peut-il travailler à temps partiel ?',jsonb_build_array('Non','Oui, sans condition','Oui, uniquement la nuit','Oui, dès le premier mois de contrat'),'Non','Le cours précise que le policier adjoint ne peut pas travailler à temps partiel. Il convient de ne pas confondre cette règle statutaire avec un simple aménagement ponctuel décidé pour les besoins du service.','Cours COP’IQ — Règles d’emploi du policier adjoint',2009),
('emploi-10','regles_emploi_pa','Règles d’emploi PA','Moyenne','Quelle affirmation décrit correctement astreinte et permanence pour un PA ?',jsonb_build_array('Pas d’astreinte ; permanence seulement sur volontariat','Astreinte et permanence obligatoires chaque semaine','Astreinte volontaire ; permanence interdite','Astreinte décidée librement par le PA'),'Pas d’astreinte ; permanence seulement sur volontariat','Le PA n’est pas soumis à l’astreinte. Une permanence reste possible sur la base du volontariat. Il peut en revanche faire l’objet d’un rappel au service selon les nécessités opérationnelles.','Cours COP’IQ — Règles d’emploi du policier adjoint',2010),
('emploi-11','regles_emploi_pa','Règles d’emploi PA','Moyenne','Pendant la période probatoire du permis, quelles missions de conduite sont en principe confiées au PA ?',jsonb_build_array('Des missions sans caractère de dangerosité','Toutes les poursuites urgentes','Uniquement les escortes à haut risque','Aucune conduite n’est jamais possible'),'Des missions sans caractère de dangerosité','Le service d’emploi apprécie les aptitudes requises selon la mission. Pendant la période probatoire, la conduite est en principe limitée aux missions de support ou de logistique dépourvues de dangerosité.','Cours COP’IQ — Règles d’emploi du policier adjoint',2011),
('emploi-12','regles_emploi_pa','Règles d’emploi PA','Difficile','Dans quel cadre le PA peut-il consulter les fichiers de police nécessaires à ses missions ?',jsonb_build_array('Pour les seuls besoins professionnels, avec secret et discrétion','Pour toute recherche concernant son entourage','Pour préparer une activité privée','Sans traçabilité dès lors qu’il est en uniforme'),'Pour les seuls besoins professionnels, avec secret et discrétion','L’accès aux fichiers est finalisé : il doit répondre à une nécessité professionnelle liée à la mission. Le secret professionnel, la discrétion et la traçabilité excluent toute consultation de curiosité.','Cours COP’IQ — Règles d’emploi du policier adjoint',2012),
('emploi-13','regles_emploi_pa','Règles d’emploi PA','Moyenne','Comment formalise-t-on un changement de service du PA dans un même département ?',jsonb_build_array('Par un avenant au contrat','Par une démission automatique','Par une nouvelle formation initiale obligatoire','Par une décision du maire'),'Par un avenant au contrat','Le policier adjoint peut occuper plusieurs postes. Lorsqu’il change de service dans le même département, la modification est formalisée par un avenant afin que son affectation contractuelle reste exacte et traçable.','Cours COP’IQ — Règles d’emploi du policier adjoint',2013),
('emploi-14','regles_emploi_pa','Règles d’emploi PA','Difficile','Quelle est la durée maximale de la sanction d’exclusion temporaire la plus courte prévue dans la gradation disciplinaire présentée ?',jsonb_build_array('3 jours','24 heures','15 jours','6 mois dans tous les cas'),'3 jours','La gradation distingue notamment une exclusion temporaire d’une durée maximale de trois jours, puis une exclusion de quatre jours à six mois. Il faut donc identifier le palier demandé avant de choisir la durée.','Cours COP’IQ — Règles d’emploi du policier adjoint',2014),
('emploi-15','regles_emploi_pa','Règles d’emploi PA','Moyenne','Quel service veille notamment au respect des lois, règlements et du code de déontologie par les policiers ?',jsonb_build_array('L’IGPN','La DGAC','La Cour des comptes uniquement','Le conseil municipal'),'L’IGPN','L’Inspection générale de la Police nationale exerce un contrôle spécialisé et mène les enquêtes qui lui sont confiées. Ce contrôle complète le contrôle hiérarchique exercé quotidiennement dans le service.','Cours COP’IQ — Règles d’emploi du policier adjoint',2015),
('horaire-01','horaires_service_sp','Horaires en sécurité publique','Facile','Quel est l’objectif principal d’un régime de travail cyclique ?',jsonb_build_array('Assurer la continuité du service public','Supprimer tout service de nuit','Reproduire strictement la semaine civile','Éviter les dimanches et jours fériés'),'Assurer la continuité du service public','Le régime cyclique organise des équipes successives de jour ou de nuit, y compris les dimanches et jours fériés. Il répond à la continuité opérationnelle et ne suit donc pas nécessairement la semaine civile.','Cours COP’IQ — Horaires en sécurité publique',2101),
('horaire-02','horaires_service_sp','Horaires en sécurité publique','Facile','Dans un régime hebdomadaire calqué sur la semaine civile, quelle alternance est prévue ?',jsonb_build_array('5 jours de travail puis 2 jours de repos consécutifs','4 jours de travail puis 4 jours de repos','2 vacations puis 3 repos','6 nuits puis 1 repos'),'5 jours de travail puis 2 jours de repos consécutifs','Le régime hebdomadaire classique suit la semaine civile avec cinq jours travaillés et deux jours de repos consécutifs. Il se distingue des cycles conçus pour une continuité jour et nuit.','Cours COP’IQ — Horaires en sécurité publique',2102),
('horaire-03','horaires_service_sp','Horaires en sécurité publique','Moyenne','Quelle alternance décrit la grande/petite semaine ?',jsonb_build_array('6 travail / 2 repos puis 4 travail / 2 repos','3 travail / 3 repos puis 2 travail / 2 repos','4 matin / 4 soir sans repos','5 travail / 5 repos'),'6 travail / 2 repos puis 4 travail / 2 repos','La grande/petite semaine alterne six jours de travail et deux repos, puis quatre jours de travail et deux repos. Il faut la distinguer des cycles 4/2 et des vacations longues.','Cours COP’IQ — Horaires en sécurité publique',2103),
('horaire-04','horaires_service_sp','Horaires en sécurité publique','Facile','Quelle pause est prévue pour une journée sans interruption ?',jsonb_build_array('20 minutes','5 minutes','45 minutes obligatoirement','2 heures'),'20 minutes','Une journée sans interruption comporte une pause obligatoire de vingt minutes, en principe placée au milieu de la journée, sous réserve des nécessités imprévisibles et impérieuses du service.','Cours COP’IQ — Horaires en sécurité publique',2104),
('horaire-05','horaires_service_sp','Horaires en sécurité publique','Moyenne','Quelle durée peut avoir la coupure méridienne d’une journée avec interruption ?',jsonb_build_array('De 45 minutes à 2 heures','Exactement 20 minutes','De 3 à 4 heures','Elle est interdite'),'De 45 minutes à 2 heures','La coupure méridienne se situe entre 11 h 30 et 14 h 30 et dure de quarante-cinq minutes à deux heures. Elle ne doit pas être confondue avec la pause de vingt minutes d’une journée continue.','Cours COP’IQ — Horaires en sécurité publique',2105),
('horaire-06','horaires_service_sp','Horaires en sécurité publique','Moyenne','Comment se compose le cycle 4/2 dit classique ?',jsonb_build_array('4 matin / 2 repos / 4 après-midi / 2 repos','2 matin / 2 après-midi / 2 repos','3 vacations / 3 repos','2 vacations / 2 repos'),'4 matin / 2 repos / 4 après-midi / 2 repos','La version classique du cycle 4/2 enchaîne quatre matinées, deux repos, quatre après-midi puis deux repos. Les versions panachée et compressée utilisent une succession différente.','Cours COP’IQ — Horaires en sécurité publique',2106),
('horaire-07','horaires_service_sp','Horaires en sécurité publique','Moyenne','Comment se compose le cycle 4/2 panaché ?',jsonb_build_array('2 matin / 2 après-midi / 2 repos','4 matin / 2 repos / 4 après-midi / 2 repos','3 nuits / 1 jour / 2 repos','2 vacations / 3 repos'),'2 matin / 2 après-midi / 2 repos','Le cycle panaché combine deux matinées, deux après-midi et deux jours de repos. L’ordre des séquences est le repère utile pour ne pas le confondre avec le cycle classique.','Cours COP’IQ — Horaires en sécurité publique',2107),
('horaire-08','horaires_service_sp','Horaires en sécurité publique','Difficile','Quelle est la durée moyenne d’une vacation dans les cycles 4/2 présentés ?',jsonb_build_array('8 h 10','9 h 31','11 h 08','12 h 08'),'8 h 10','Les cycles 4/2 reposent sur une vacation moyenne de huit heures dix. Les durées de onze heures huit, douze heures huit et neuf heures trente et une correspondent à d’autres organisations.','Cours COP’IQ — Horaires en sécurité publique',2108),
('horaire-09','horaires_service_sp','Horaires en sécurité publique','Moyenne','Que signifie un cycle 2/2 ?',jsonb_build_array('2 vacations puis 2 jours de repos','2 matinées puis 2 après-midi','2 semaines puis 2 repos','2 heures de travail puis 2 heures de pause'),'2 vacations puis 2 jours de repos','La notation décrit directement la succession : deux vacations sont suivies de deux jours de repos. Elle ne précise pas à elle seule si l’équipe travaille de jour ou de nuit.','Cours COP’IQ — Horaires en sécurité publique',2109),
('horaire-10','horaires_service_sp','Horaires en sécurité publique','Moyenne','Que signifie un cycle 3/3 ?',jsonb_build_array('3 vacations puis 3 jours de repos','3 matinées puis 3 après-midi sans repos','3 heures de service puis 3 heures libres','3 semaines de jour puis 3 semaines de nuit'),'3 vacations puis 3 jours de repos','Dans le cycle 3/3, trois vacations précèdent trois jours de repos. Les deux premiers repos ont la qualification de repos compensateurs dans la présentation du cours.','Cours COP’IQ — Horaires en sécurité publique',2110),
('horaire-11','horaires_service_sp','Horaires en sécurité publique','Difficile','Combien de pauses de 20 minutes prévoient les cycles à vacation de 11 h 08 ou 12 h 08 ?',jsonb_build_array('Deux','Aucune','Une','Quatre'),'Deux','Ces vacations longues prévoient deux pauses de vingt minutes qui divisent la journée en trois périodes de travail équilibrées. Ce dispositif est différent de la pause unique d’une journée continue ordinaire.','Cours COP’IQ — Horaires en sécurité publique',2111),
('horaire-12','horaires_service_sp','Horaires en sécurité publique','Difficile','Quelle est la durée moyenne d’une vacation dans le cycle dit « vacation forte » ?',jsonb_build_array('9 h 31','8 h 10','11 h 08 exactement','12 h 08 exactement'),'9 h 31','Le cycle « vacation forte » 2/2/3/2/3/2 prévoit une durée moyenne de neuf heures trente et une. Sa finalité est de renforcer la présence de plusieurs groupes sur certaines vacations.','Cours COP’IQ — Horaires en sécurité publique',2112),
('horaire-13','horaires_service_sp','Horaires en sécurité publique','Moyenne','Quel jour constitue en principe le repos légal en régime hebdomadaire ?',jsonb_build_array('Le dimanche','Le samedi uniquement','Le lundi uniquement','N’importe quel jour choisi librement'),'Le dimanche','En régime hebdomadaire, le repos légal est en principe le dimanche. Le samedi ou le lundi peut correspondre au repos compensateur selon l’organisation retenue.','Cours COP’IQ — Horaires en sécurité publique',2113),
('horaire-14','horaires_service_sp','Horaires en sécurité publique','Moyenne','À combien correspondent en principe les congés annuels d’un agent en régime hebdomadaire ?',jsonb_build_array('5 fois les obligations hebdomadaires, soit 25 jours ouvrés','10 jours ouvrés','12 jours calendaires','52 jours ouvrés'),'5 fois les obligations hebdomadaires, soit 25 jours ouvrés','Le calcul de principe correspond à cinq fois les obligations hebdomadaires, soit vingt-cinq jours ouvrés pour un rythme de cinq jours. Les autres repos et compensations relèvent de catégories distinctes.','Cours COP’IQ — Horaires en sécurité publique',2114)
), tracks(track,module,source_path) as (
values
('gpx','gpx_institutions_valeurs_quiz_institutions_valeurs_quiz_organisation_page','lib/content/gpx_scolarite/institutions_valeurs/quiz_institutions_valeurs/quiz_organisation_page.dart'),
('pa','pa_institutions_valeurs_quiz_pa_quiz_organisation_page','lib/content/pa_scolarite/institutions_valeurs_quiz/pa_quiz_organisation_page.dart')
)
insert into public.quiz_scolarite_questions(module,track,category,difficulty,question,options,answer,explanation,legal_ref,position,is_active,publication_status,published_at,source_path,source_hash,source_question_key,metadata,revision)
select t.module,t.track,q.category,q.difficulty,q.question,q.options,q.answer,q.explanation,q.legal_ref,q.position,true,'published',now(),t.source_path,md5(q.stable_key||':'||q.answer),'organisation-'||q.stable_key,
jsonb_build_object('schema_version',2,'content_version',1,'stable_key','organisation-'||q.stable_key,'course_key','organisation_police_nationale','chapter_key',q.chapter_key,'question_type','multiple_choice','tags',jsonb_build_array(q.chapter_key),'source_reference',q.legal_ref),1
from questions q cross join tracks t
on conflict (source_path,source_question_key) where source_path is not null and source_question_key is not null
do update set category=excluded.category,difficulty=excluded.difficulty,question=excluded.question,options=excluded.options,answer=excluded.answer,explanation=excluded.explanation,legal_ref=excluded.legal_ref,metadata=excluded.metadata,is_active=true,publication_status='published',updated_at=now();

-- Garantit une couverture minimale pour les chapitres déjà riches mais anciennement mal classés.
with deficits(track, chapter_key, missing) as (
  select t.track, c.chapter_key, greatest(0, 15-count(q.id))::int
  from (values ('gpx'),('pa')) t(track)
  cross join (values ('dgsi'),('prefecture_police'),('organigramme_mi'),('organigrammes_pn')) c(chapter_key)
  left join public.quiz_scolarite_questions q on q.track=t.track and q.metadata->>'chapter_key'=c.chapter_key and q.is_active and q.publication_status='published'
  group by t.track,c.chapter_key
), candidates as (
  select q.id,d.chapter_key,row_number() over(partition by d.track,d.chapter_key order by q.position,q.id) rn,d.missing
  from deficits d join public.quiz_scolarite_questions q on q.track=d.track and q.metadata->>'chapter_key'='organisation_pn'
  where (d.chapter_key='dgsi' and q.category ilike '%DGSI%')
     or (d.chapter_key='prefecture_police' and q.category ilike '%Préfecture%')
     or (d.chapter_key like 'organigramme%' and q.category ~* 'Organisation PN — (DGPN|Directions|DNPAF|DNPJ|DNSP|DRHFS|IGPN|CRS|ADP|SDLP)')
)
update public.quiz_scolarite_questions q set metadata=q.metadata||jsonb_build_object('chapter_key',c.chapter_key),updated_at=now()
from candidates c where q.id=c.id and c.rn<=c.missing;
