-- Derniers compléments de couverture : DGSI et Préfecture de Police.
with questions(stable_key, chapter_key, category, difficulty, question, options, answer, explanation, legal_ref, position) as (
values
('dgsi-coverage-15','dgsi','DGSI — Missions','Difficile','Dans ses domaines de compétence, à quelle autre mission la DGSI peut-elle concourir en plus du renseignement ?',jsonb_build_array('À l’exercice de missions de police judiciaire','À la délivrance des permis de conduire','À la gestion des transports municipaux','À la police administrative des débits de boissons'),'À l’exercice de missions de police judiciaire','La DGSI recherche, centralise et exploite le renseignement intéressant la sécurité nationale, mais elle peut aussi concourir à des missions de police judiciaire dans ses domaines de compétence. Cette articulation permet de détecter une menace, de la documenter puis de participer à sa judiciarisation.','Cours COP’IQ — Direction générale de la Sécurité intérieure',2201),
('pp-coverage-13','prefecture_police','Préfecture de Police — Compétence','Moyenne','Sur quels départements le préfet de police exerce-t-il les attributions présentées pour l’administration de la police, en plus de Paris ?',jsonb_build_array('Hauts-de-Seine, Seine-Saint-Denis et Val-de-Marne','Yvelines, Essonne et Val-d’Oise','Seine-et-Marne, Oise et Eure','Tous les départements français'),'Hauts-de-Seine, Seine-Saint-Denis et Val-de-Marne','Le périmètre présenté associe Paris et les trois départements de la petite couronne : Hauts-de-Seine, Seine-Saint-Denis et Val-de-Marne. Il ne faut pas le confondre avec la zone de défense et de sécurité de Paris, qui couvre les huit départements d’Île-de-France.','Cours COP’IQ — Préfecture de Police',2202),
('pp-coverage-14','prefecture_police','Préfecture de Police — Transports','Difficile','Quel rôle le préfet de police exerce-t-il dans les transports ferrés d’Île-de-France ?',jsonb_build_array('Le commandement opérationnel unique de la sécurité','La fixation du prix de tous les billets','La conduite quotidienne de chaque train','La construction exclusive des infrastructures'),'Le commandement opérationnel unique de la sécurité','Le préfet de police est responsable du commandement opérationnel unique de la sécurité dans les transports ferrés franciliens. Cette fonction de coordination de la sécurité ne doit pas être confondue avec l’exploitation commerciale ou la construction du réseau.','Cours COP’IQ — Préfecture de Police',2203),
('pp-coverage-15','prefecture_police','Préfecture de Police — Attributions','Moyenne','Laquelle de ces missions fait partie des attributions de la Préfecture de Police ?',jsonb_build_array('Prévenir les événements troublant l’ordre public','Définir les programmes scolaires nationaux','Administrer les juridictions judiciaires','Fixer la politique monétaire'),'Prévenir les événements troublant l’ordre public','Parmi ses attributions figurent la sécurité des personnes et des biens, la sécurité civile, la circulation, certaines polices administratives et la prévention des troubles à l’ordre public. Les autres propositions relèvent d’autorités entièrement différentes.','Cours COP’IQ — Préfecture de Police',2204)
), tracks(track,module,source_path) as (
values
('gpx','gpx_institutions_valeurs_quiz_institutions_valeurs_quiz_organisation_page','lib/content/gpx_scolarite/institutions_valeurs/quiz_institutions_valeurs/quiz_organisation_page.dart'),
('pa','pa_institutions_valeurs_quiz_pa_quiz_organisation_page','lib/content/pa_scolarite/institutions_valeurs_quiz/pa_quiz_organisation_page.dart')
)
insert into public.quiz_scolarite_questions(module,track,category,difficulty,question,options,answer,explanation,legal_ref,position,is_active,publication_status,published_at,source_path,source_hash,source_question_key,metadata,revision)
select t.module,t.track,q.category,q.difficulty,q.question,q.options,q.answer,q.explanation,q.legal_ref,q.position,true,'published',now(),t.source_path,md5(q.stable_key||':'||q.answer),'organisation-'||q.stable_key,jsonb_build_object('schema_version',2,'content_version',1,'stable_key','organisation-'||q.stable_key,'course_key','organisation_police_nationale','chapter_key',q.chapter_key,'question_type','multiple_choice','tags',jsonb_build_array(q.chapter_key),'source_reference',q.legal_ref),1
from questions q cross join tracks t
on conflict (source_path,source_question_key) where source_path is not null and source_question_key is not null
do update set question=excluded.question,options=excluded.options,answer=excluded.answer,explanation=excluded.explanation,metadata=excluded.metadata,is_active=true,publication_status='published',updated_at=now();
